graph LR
    A(("Java SE 17<br/>(Release: September 2021)")):::main
    A --> F_1:::background 
    A --> F_2:::background 
    A --> F_3:::background 
    A --> F_4:::background 
    A --> F_5:::background 
    A --> F_6:::background 
    A --> F_7:::background 
    A --> F_8:::background 
    A --> F_9:::background 

    subgraph F_1["Sealed Classes"]
    direction TB
        F11("Restrict class hierarchies")
    end

    subgraph F_2["Enhanced Pattern Matching for instanceof"]
    direction TB
        F21("Simplifies instanceof and cast combination")
    end
    
    subgraph F_3["Pattern Matching for switch (Preview)"]
    direction TB
        F31("Flexible pattern matching for switch")
    end
    
    subgraph F_4["Records"]
    direction TB
        F41("Immutable data carrier classes")
        F42("Automatic implementations of equals, hashCode, and toString")
    end
    
    subgraph F_5["Text Blocks"]
    direction TB
        F51("Multi-line string literals for readability")
    end

    subgraph F_6["Strong Encapsulation"]
    direction TB
        F61("Fully encapsulated internal APIs")
        F62("Improves security by restricting access to non-public APIs")
    end

    subgraph F_7["Foreign Function & Memory"]
    direction TB
        F71("Interoperate with native code and memory")
        F72("Allows access to native libraries and data outside JVM")
    end

    subgraph F_8["Vector API (Incubator)"]
    direction TB
        F81("APIs for vector computations")
        F82("Supports SIMD \(Single Instruction, Multiple Data\) instructions")
    end

    subgraph F_9["Deprecations and Removals"]
    direction TB
        F91("Removal of outdated features")
        F92("Deprecation of Applet API and RMI Activation")
    end

classDef main fill:#008c31,font-size:1.4rem,stroke-width: 0.2rem;
classDef background fill:#0089a8,fill-opacity: 0.2;
