---
title: JVM Garbage Collector Types
---
flowchart TB
  A((JVM GC Types))
  A --> B1(Serial Garbage Collector)
  A --> B2(Parallel Garbage Collector)
  A --> B3(G1 Garbage Collector)
  A --> B4(Z Garbage Collector)

style A fill:#008c31,font-size:1rem,stroke-width: 0.2rem;
style B1 stroke:#2eab00,stroke-width: 0.2rem;
style B2 stroke:#2eab00,stroke-width: 0.2rem;
style B3 stroke:#2eab00,stroke-width: 0.2rem;
style B4 stroke:#2eab00,stroke-width: 0.2rem;
