---
title: Serial Garbage Collector
---
flowchart TB
  G((Serial Garbage<br/>Collector))
  G --> A1(<ins>**Simplest implementation.**</ins><br/>Works with a single thread)
  G --> D1(<ins>**Freezes all application threads when it runs.**</ins><br/>It's not good idea to use it with multi-threaded apps, like server environments)
  G --> N1(Good choice <ins>**for most applications that don’t have small pause time requirements and run on client-style machines.**</ins>)
  G --> C1("<ins>**JVM Argument:**</ins><br/>java -XX:+UseSerialGC -jar Application.java")

style G fill:#008c31,font-size:1rem,stroke-width: 0.2rem;
style A1 stroke:#2eab00,stroke-width: 0.2rem;
style D1 stroke:#a81f00,stroke-width: 0.2rem;
style N1 stroke:#0089a8,stroke-width: 0.2rem;
style C1 stroke-width: 0.2rem;
